### ISSUE TITLE
No Measure Option available

### ISSUE THREAD

**Issue by makrawal** [ralfbecher/QlikSense_Extension_CorrelationMatrix#1]
Hi,
I want to use your extension but I cannot enter any measure.
It only shows 3 dimensions to be entered.
I am attaching screenshot for your understanding.
Please fix this issue.

Thanks
Mayank Rawal
![1](https://user-images.githubusercontent.com/15025950/29924482-af4ced1a-8e7a-11e7-99cf-7400892a1114.png)
![2](https://user-images.githubusercontent.com/15025950/29924560-fa5c1e66-8e7a-11e7-8ddf-d5c06e375772.PNG)

**Comment by ralfbecher** [comment]
This is not an issue since the extension uses Qlik's Correl( ) function in the background.
